name: GitHub Actions Demo

on:
  push:
    branches:
      - actions

jobs:
  explore-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements_dev.txt

      - name: Run tests
        run: |
          pytest

      - name: Code quality check with flake8 and black
        run: |
          flake8 --max-line-length=120 --ignore=D101,D104,D212,D200,E203,W293,D412,W503 mkdocs_with_confluence/
          black --check --line-length=120 mkdocs_with_confluence/
